# Generated by Django 2.2.3 on 2019-08-27 12:27

import aukcije.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('adresa', models.CharField(max_length=45)),
                ('grad', models.CharField(max_length=45)),
                ('opstina', models.CharField(max_length=45)),
                ('drzava', models.CharField(max_length=45)),
                ('telefon', models.CharField(max_length=45)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aukcija',
            fields=[
                ('idaukcije', models.AutoField(db_column='idAukcije', primary_key=True, serialize=False)),
                ('nazivpredmeta', models.CharField(db_column='nazivPredmeta', max_length=45, verbose_name='Naziv predmeta')),
                ('datumpocetka', models.DateTimeField(auto_now_add=True, db_column='datumPocetka', verbose_name='Datum pocetka')),
                ('datumisteka', models.DateTimeField(db_column='datumIsteka', verbose_name='Datum isteka')),
                ('aktuelnaponuda', models.IntegerField(db_column='aktuelnaPonuda', verbose_name='Aktuelna ponuda')),
                ('kupiodmah', models.BooleanField(db_column='kupiOdmah', verbose_name='Kupi odmah')),
                ('kupiodmahcena', models.IntegerField(blank=True, db_column='kupiOdmahCena', null=True, verbose_name='Kupi odmah cena')),
                ('opispredmeta', models.TextField(blank=True, db_column='opisPredmeta', max_length=200, null=True, verbose_name='Opis predmeta')),
                ('aktivna', models.BooleanField(default=True)),
                ('proizvodjac', models.CharField(blank=True, max_length=45, null=True)),
                ('idprodavca', models.ForeignKey(db_column='idProdavca', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Prodavac')),
            ],
        ),
        migrations.CreateModel(
            name='Osobina',
            fields=[
                ('idosobina', models.AutoField(db_column='idOsobina', primary_key=True, serialize=False)),
                ('nazivosobine', models.CharField(db_column='nazivOsobine', max_length=45, verbose_name='Naziv osobine')),
            ],
        ),
        migrations.CreateModel(
            name='PonudjeneVrednosti',
            fields=[
                ('idponudjenevrednosti', models.AutoField(db_column='idPonudjeneVrednosti', primary_key=True, serialize=False)),
                ('vrednost', models.CharField(max_length=45, verbose_name='Ponudjena vrednost')),
                ('idosobine', models.ForeignKey(db_column='idOsobine', on_delete=django.db.models.deletion.CASCADE, to='aukcije.Osobina', verbose_name='Osobina')),
            ],
            options={
                'unique_together': {('idponudjenevrednosti', 'idosobine')},
            },
        ),
        migrations.CreateModel(
            name='Ponuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True, db_column='datumPonude', verbose_name='Datum ponude')),
                ('aukcija', models.ForeignKey(db_column='idAukcije', on_delete=django.db.models.deletion.DO_NOTHING, to='aukcije.Aukcija', verbose_name='Aukcija')),
                ('korisnik', models.ForeignKey(db_column='idKorisnik', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='OdabraneVrednostiPredmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aukcija', models.OneToOneField(db_column='idAukcije', on_delete=django.db.models.deletion.CASCADE, to='aukcije.Aukcija', verbose_name='Aukcija')),
                ('pv', models.ManyToManyField(to='aukcije.PonudjeneVrednosti', verbose_name='Ponudjena vrednost')),
            ],
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('idkategorija', models.AutoField(db_column='idKategorija', primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=45)),
                ('idnadkategorije', models.ForeignKey(blank=True, db_column='idNadKategorije', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aukcije.Kategorija', verbose_name='Nadkategorija')),
                ('osobine', models.ManyToManyField(blank=True, to='aukcije.Osobina')),
            ],
        ),
        migrations.AddField(
            model_name='aukcija',
            name='kategorije',
            field=models.ManyToManyField(to='aukcije.Kategorija'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='lista_zelja',
            field=models.ManyToManyField(blank=True, related_name='lista_zelja', to='aukcije.Aukcija', verbose_name='Lista zelja'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('idslika', models.AutoField(db_column='idSlika', primary_key=True, serialize=False)),
                ('slika', models.ImageField(upload_to=aukcije.models.Slika.user_directory_path)),
                ('idaukcije', models.ForeignKey(db_column='idAukcije', on_delete=django.db.models.deletion.CASCADE, to='aukcije.Aukcija', verbose_name='Aukcija')),
            ],
            options={
                'unique_together': {('idslika', 'idaukcije')},
            },
        ),
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('idaukcije', models.OneToOneField(db_column='idAukcije', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aukcije.Aukcija', verbose_name='Aukcija')),
                ('krajnjacena', models.IntegerField(db_column='krajnjaCena', verbose_name='Krajnja cena')),
                ('idkupca', models.ForeignKey(db_column='idKupca', on_delete=django.db.models.deletion.DO_NOTHING, related_name='kupac', to=settings.AUTH_USER_MODEL, verbose_name='Kupac')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.CharField(max_length=45)),
                ('komentar', models.CharField(max_length=45)),
                ('datum', models.DateTimeField()),
                ('ocenio', models.CharField(max_length=3)),
                ('idocenjenog', models.ForeignKey(db_column='idOcenjenog', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ocenjeni', to=settings.AUTH_USER_MODEL, verbose_name='Ocenjeni')),
                ('idocenjivac', models.ForeignKey(db_column='idOcenjivac', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ocenjivac', to=settings.AUTH_USER_MODEL, verbose_name='Ocenjivac')),
                ('idaukcija', models.ForeignKey(db_column='idAukcija', on_delete=django.db.models.deletion.DO_NOTHING, to='aukcije.Prodaja', verbose_name='Aukcija')),
            ],
            options={
                'unique_together': {('idaukcija', 'idocenjivac', 'idocenjenog')},
            },
        ),
    ]
