# Generated by Django 2.2.3 on 2019-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aukcije', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aukcija',
            name='aktuelnaponuda',
            field=models.PositiveIntegerField(db_column='aktuelnaPonuda', verbose_name='Aktuelna ponuda'),
        ),
        migrations.AlterField(
            model_name='aukcija',
            name='kupiodmahcena',
            field=models.PositiveIntegerField(blank=True, db_column='kupiOdmahCena', null=True, verbose_name='Kupi odmah cena'),
        ),
        migrations.AlterField(
            model_name='ponuda',
            name='cena',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prodaja',
            name='krajnjacena',
            field=models.PositiveIntegerField(db_column='krajnjaCena', verbose_name='Krajnja cena'),
        ),
    ]
