# Generated by Django 2.2.3 on 2019-09-02 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aukcije', '0002_auto_20190828_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodaja',
            name='datum',
            field=models.DateTimeField(db_column='datumProdaje', default=django.utils.timezone.now, verbose_name='Datum prodaje'),
        ),
    ]
