# Generated by Django 2.2.3 on 2019-09-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aukcije', '0004_auto_20190902_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='idaukcija',
            new_name='prodaja',
        ),
        migrations.AlterUniqueTogether(
            name='ocena',
            unique_together={('prodaja', 'idocenjivac', 'idocenjenog')},
        ),
    ]
