# Generated by Django 2.2.3 on 2019-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aukcije', '0005_auto_20190904_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
