# Generated by Django 2.2.3 on 2019-09-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aukcije', '0006_auto_20190904_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='idocenjenog',
            new_name='ocenjeni',
        ),
        migrations.RenameField(
            model_name='ocena',
            old_name='idocenjivac',
            new_name='ocenjivac',
        ),
        migrations.AlterUniqueTogether(
            name='ocena',
            unique_together={('prodaja', 'ocenjivac', 'ocenjeni')},
        ),
    ]
