# Generated by Django 2.2.3 on 2019-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aukcije', '0010_auto_20190904_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodaja',
            name='krajnjacena',
            field=models.PositiveIntegerField(db_column='krajnjaCena', verbose_name='Krajnja cena'),
        ),
    ]
